### ISSUE TITLE
Implementar ejemplo con leaflet utilizando tiles de San Pedro

### ISSUE THREAD

**Issue by mdumrauf** [indec-it/geo-viewer#1]

**Comment by manureta** [comment]
Se modifico directamente en master el leafleat.html base, 
Se se crearon archivos para definir proyecciones y capas en archivos separados.
Se establecio el mapa en Sistema de coordenadas planas POSGAR 94 Faja 5, correspondiente a Bs As.
Se definio el bounds de acuerdo a la imagen tileada de San Pedro.
Se agrego servicio WMS en EPSG:22185, para verificar coincidencia.
Se agregaron algunos tiles de ejemplo y un marcador al mapa donde funciona el ejemplo.
